export const widgets = {
  apple_music: require('./apple_music.png'),
  pinterest: require('./pinterest.png'),
  snapchat: require('./snapchat.png'),
  soundcloud: require('./soundcloud.png'),
  deezer: require('./deezer.png'),
  spotify: require('./spotify.png'),
  tik_tok: require('./tik_tok.png'),
  twitch: require('./twitch.png'),
  instagram: require('./instagram.png'),
  tik_tok_link: require('./tik_tok_link.png'),
  youtube_link: require('./youtube.png'),
  depop: require('./depop.png'),
  etsy: require('./etsy.png'),
  apple_podcast: require('./apple_podcast.png'),
  app_store: require('./app_store.png'),
  shopify: require('./shopify.png'),
  amazon: require('./amazon.png'),
  poshmark: require('./poshmark.png'),
  website: require('./website.png'),
  email: require('./email.png'),
  article: require('./article.png'),
  liketoknowit: require('./liketoknowit.png'),
};
