import { images } from 'assets/images';
import {
  AMAZON,
  APP_STORE,
  APPLE_MUSIC,
  APPLE_PODCAST,
  DEPOP,
  ETSY,
  POSHMARK,
  DEEZER,
  SHOPIFY,
  SOUNDCLOUD,
  SPOTIFY,
  TIK_TOK,
  INSTA_GRAM,
  SNAPCHAT,
  TWITTER,
  TWITCH,
  WEBSITE,
  YOUTUBE,
  FACEBOOK,
  DISCORD,
  EMAIL,
  ONLYFANS,
  VSCO,
  TIDAL,
  YOUTUBEMUSIC,
  PINTEREST,
  LIKETOKNOWIT,
} from 'constants/regex';
import {
  ApplicationLinkWidgetLinkTypes,
  WidgetType,
  VideoLinkWidgetLinkTypes,
  ApplicationLinkWidgetTypes,
  SocialMediaTypes,
  GenericLinkWidgetTypes,
} from 'types';

export const TaggShopGradientBg = {
  LikeToKnowIt: {
    start: '#F0F0F0',
    end: '#000000',
  },
  Pinterest: {
    start: '#E61E27',
    end: '#6D0005',
  },
  YOUTUBEMUSIC: {
    start: '#FF0000',
    end: '#9F0000',
  },
  TIDAL: {
    start: '#262626',
    end: '#000000',
  },
  VSCO: {
    start: '#F0F0F0',
    end: '#000000',
  },
  OnlyFans: {
    start: '#018CCF',
    end: '#023D59',
  },
  Email: {
    start: '#96080A',
    end: '#670203',
  },
  Discord: {
    start: '#7984FF',
    end: '#030F8E',
  },
  Website: {
    start: '#C0D6FF',
    end: '#698DD3',
  },
  Instagram: {
    start: '#FF0CD5',
    end: '#A8228E',
  },
  TikTok: {
    start: '#262626',
    end: '#000000',
  },
  Youtube: {
    start: '#FF0000',
    end: '#9F0000',
  },
  Snapchat: {
    start: '#FFE600',
    end: '#B69903',
  },
  MomentTagg: {
    start: '#F0F0F0',
    end: '#000000',
  },
  Twitter: {
    start: '#1DA1F3',
    end: '#027AC3',
  },
  Twitch: {
    start: '#751CFA',
    end: '#5924A7',
  },
  Deezer: {
    start: '#262626',
    end: '#000000',
  },
  Spotify: {
    start: '#00BC43',
    end: '#018931',
  },
  AppleMusic: {
    start: '#DB071E',
    end: '#75020E',
  },
  Soundcloud: {
    start: '#FF7500',
    end: '#E23000',
  },
  Article: {
    start: '#986BE0',
    end: '#421566',
  },
  Depop: {
    start: '#FF2300',
    end: '#8D1603',
  },
  Etsy: {
    start: '#F1641D',
    end: '#BC4002',
  },
  Amazon: {
    start: '#F0F0F0',
    end: '#000000',
  },
  AmazonAffiliate: {
    start: '#F0F0F0',
    end: '#000000',
  },
  ApplePodcast: {
    start: '#8829CF',
    end: '#7100BF',
  },
  Facebook: {
    start: '#1877F2',
    end: '#0C5BC0',
  },
  Poshmark: {
    start: '#9D3040',
    end: '#852533',
  },
  AppStore: {
    start: '#1BA5F7',
    end: '#0958C5',
  },
};

export const TaggShopData: WidgetType[] = [
  {
    id: '',
    img: images.socials.website,
    title: 'Website',
    subTitle: 'Utility Tagg',
    link_type: GenericLinkWidgetTypes.WEBSITE,
    type: ApplicationLinkWidgetTypes.GENERIC_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Website.start,
    item_color_end: TaggShopGradientBg.Website.end,
    widgetLogo: images.widgetLogo.website,
  },
  {
    id: '',
    img: images.socials.instagram,
    title: 'Instagram',
    subTitle: 'Social Media Tagg',
    link_type: SocialMediaTypes.INSTAGRAM,
    type: ApplicationLinkWidgetTypes.SOCIAL,
    locked: false,
    item_color_start: TaggShopGradientBg.Instagram.start,
    item_color_end: TaggShopGradientBg.Instagram.end,
    widgetLogo: images.widgetLogo.instagram,
  },
  {
    id: '',
    img: images.socials.tiktok,
    title: 'TikTok',
    subTitle: 'Social Media Tagg',
    link_type: VideoLinkWidgetLinkTypes.TIKTOK,
    type: ApplicationLinkWidgetTypes.VIDEO_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.TikTok.start,
    item_color_end: TaggShopGradientBg.TikTok.end,
    widgetLogo: images.widgetLogo.tiktok,
  },
  {
    id: '',
    img: images.socials.youtube,
    title: 'Youtube',
    subTitle: 'Video Tagg',
    link_type: VideoLinkWidgetLinkTypes.YOUTUBE,
    type: ApplicationLinkWidgetTypes.VIDEO_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Youtube.start,
    item_color_end: TaggShopGradientBg.Youtube.end,
    widgetLogo: images.widgetLogo.youtube,
  },
  {
    id: '',
    img: images.socials.snapchat,
    title: 'Snapchat',
    subTitle: 'Social Media Tagg',
    link_type: SocialMediaTypes.SNAPCHAT,
    type: ApplicationLinkWidgetTypes.SOCIAL,
    locked: false,
    item_color_start: TaggShopGradientBg.Snapchat.start,
    item_color_end: TaggShopGradientBg.Snapchat.end,
    widgetLogo: images.widgetLogo.snapchat,
  },
  {
    id: '',
    img: images.socials.twitter,
    title: 'Twitter',
    subTitle: 'Social Media Tagg',
    link_type: SocialMediaTypes.TWITTER,
    type: ApplicationLinkWidgetTypes.SOCIAL,
    locked: false,
    item_color_start: TaggShopGradientBg.Twitter.start,
    item_color_end: TaggShopGradientBg.Twitter.end,
    widgetLogo: images.widgetLogo.twitter,
  },
  {
    id: '',
    img: images.socials.twitch,
    title: 'Twitch',
    subTitle: 'Streaming Tagg',
    link_type: VideoLinkWidgetLinkTypes.TWITCH,
    type: ApplicationLinkWidgetTypes.VIDEO_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Twitch.start,
    item_color_end: TaggShopGradientBg.Twitch.end,
    widgetLogo: images.widgetLogo.twitch,
  },
  {
    id: '',
    img: images.socials.vsco,
    title: 'VSCO',
    subTitle: 'Utility',
    link_type: VideoLinkWidgetLinkTypes.VSCO,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.VSCO.start,
    item_color_end: TaggShopGradientBg.VSCO.end,
    widgetLogo: images.widgetLogo.vsco,
  },
  {
    id: '',
    img: images.socials.email,
    title: 'Email',
    subTitle: 'Utility Tagg',
    link_type: GenericLinkWidgetTypes.EMAIL,
    type: ApplicationLinkWidgetTypes.GENERIC_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Email.start,
    item_color_end: TaggShopGradientBg.Email.end,
    widgetLogo: images.widgetLogo.email,
  },
  {
    id: '',
    img: images.socials.spotify,
    title: 'Spotify',
    subTitle: 'Music Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.SPOTIFY,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Spotify.start,
    item_color_end: TaggShopGradientBg.Spotify.end,
    widgetLogo: images.widgetLogo.spotify,
  },
  {
    id: '',
    img: images.socials.apple_music,
    title: 'Apple Music',
    subTitle: 'Music Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.APPLE_MUSIC,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.AppleMusic.start,
    item_color_end: TaggShopGradientBg.AppleMusic.end,
    widgetLogo: images.widgetLogo.appleMusic,
  },
  {
    id: '',
    img: images.socials.Tidal,
    title: 'Tidal',
    subTitle: 'Music',
    link_type: ApplicationLinkWidgetLinkTypes.TIDAL,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.TIDAL.start,
    item_color_end: TaggShopGradientBg.TIDAL.end,
    widgetLogo: images.widgetLogo.Tidal,
  },
  {
    id: '',
    img: images.socials.deezer,
    title: 'Deezer',
    subTitle: 'Music Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.DEEZER,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Deezer.start,
    item_color_end: TaggShopGradientBg.Deezer.end,
    widgetLogo: images.widgetLogo.deezer,
  },
  {
    id: '',
    img: images.socials.Youtubemusic,
    title: 'Youtube Music',
    subTitle: 'Music',
    link_type: ApplicationLinkWidgetLinkTypes.YOUTUBE_MUSIC,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.YOUTUBEMUSIC.start,
    item_color_end: TaggShopGradientBg.YOUTUBEMUSIC.end,
    widgetLogo: images.widgetLogo.Youtubemusic,
  },
  {
    id: '',
    img: images.socials.soundcloud,
    title: 'Soundcloud',
    subTitle: 'Music Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.SOUNDCLOUD,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Soundcloud.start,
    item_color_end: TaggShopGradientBg.Soundcloud.end,
    widgetLogo: images.widgetLogo.soundcloud,
  },
  {
    id: '',
    img: images.socials.article,
    title: 'Article',
    subTitle: 'Utility Tagg',
    link_type: GenericLinkWidgetTypes.ARTICLE,
    type: ApplicationLinkWidgetTypes.GENERIC_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Article.start,
    item_color_end: TaggShopGradientBg.Article.end,
    widgetLogo: images.widgetLogo.article,
  },
  {
    id: '',
    img: images.socials.depop,
    title: 'Depop',
    subTitle: 'Product Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.DEPOP,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Depop.start,
    item_color_end: TaggShopGradientBg.Depop.end,
    widgetLogo: images.widgetLogo.depop,
  },
  // {
  //   id: 8,
  //   img: images.widgets.instagram,
  //   title: 'Instagram',
  //   subTitle: 'SOCIAL MEDIA TAGG',
  //     linkType: VideoLinkWidgetLinkTypes.INSTAGRAM,
  //   locked: false,
  // },
  // {
  //   id: '9',
  //   img: images.widgets.tik_tok_link,
  //   title: 'TikTok',
  //   subTitle: 'Video TAGG',
  //   link_type: VideoLinkWidgetLinkTypes.TIKTOK,
  //   type: ApplicationLinkWidgetTypes.VIDEO_LINK,
  //   locked: false,
  // },
  {
    id: '',
    img: images.socials.etsy,
    title: 'Etsy',
    subTitle: 'Product Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.ETSY,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Etsy.start,
    item_color_end: TaggShopGradientBg.Etsy.end,
    widgetLogo: images.widgetLogo.etsy,
  },
  {
    id: '',
    img: images.socials.likeToKnowIt,
    title: 'LikeToKnowIt',
    subTitle: 'Utility Tagg',
    link_type: GenericLinkWidgetTypes.LIKETOKNOWIT,
    type: ApplicationLinkWidgetTypes.GENERIC_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.LikeToKnowIt.start,
    item_color_end: TaggShopGradientBg.LikeToKnowIt.end,
    widgetLogo: images.widgetLogo.liketoknowttLogo,
  },
  {
    id: '',
    img: images.socials.Pinterest,
    title: 'Pinterest',
    subTitle: 'Utility',
    link_type: VideoLinkWidgetLinkTypes.PINTEREST,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Pinterest.start,
    item_color_end: TaggShopGradientBg.Pinterest.end,
    widgetLogo: images.widgetLogo.Pinterest,
  },
  {
    id: '',
    img: images.socials.OnlyFans,
    title: 'OnlyFans',
    subTitle: 'Utility',
    link_type: VideoLinkWidgetLinkTypes.ONLYFANS,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.OnlyFans.start,
    item_color_end: TaggShopGradientBg.OnlyFans.end,
    widgetLogo: images.socials.OnlyFans,
  },
  {
    id: '',
    img: images.socials.amazon,
    title: 'Amazon',
    subTitle: 'Product Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.AMAZON,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Amazon.start,
    item_color_end: TaggShopGradientBg.Amazon.end,
    widgetLogo: images.widgetLogo.amazon,
  },
  {
    id: '',
    img: images.socials.amazon,
    title: 'Amazon Affiliate',
    subTitle: 'Product Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.AMAZON_AFFILIATE,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.AmazonAffiliate.start,
    item_color_end: TaggShopGradientBg.AmazonAffiliate.end,
    widgetLogo: images.widgetLogo.amazon,
  },
  {
    id: '',
    img: images.socials.applePodcast,
    title: 'Apple Podcast',
    subTitle: 'Music Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.APPLE_PODCAST,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.ApplePodcast.start,
    item_color_end: TaggShopGradientBg.ApplePodcast.end,
    widgetLogo: images.widgetLogo.applePodcast,
  },
  {
    id: '',
    img: images.socials.discord,
    title: 'Discord',
    subTitle: 'Utility Tagg',
    link_type: GenericLinkWidgetTypes.DISCORD,
    type: ApplicationLinkWidgetTypes.GENERIC_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Discord.start,
    item_color_end: TaggShopGradientBg.Discord.end,
    widgetLogo: images.widgetLogo.discord,
  },
  {
    id: '',
    img: images.socials.facebookIcon,
    title: 'Facebook',
    subTitle: 'Social Media Tagg',
    link_type: SocialMediaTypes.FACEBOOK,
    type: ApplicationLinkWidgetTypes.SOCIAL,
    locked: false,
    item_color_start: TaggShopGradientBg.Facebook.start,
    item_color_end: TaggShopGradientBg.Facebook.end,
    widgetLogo: images.widgetLogo.facebook,
  },
  {
    id: '',
    img: images.socials.poshmark,
    title: 'Poshmark',
    subTitle: 'Product Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.POSHMARK,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.Poshmark.start,
    item_color_end: TaggShopGradientBg.Poshmark.end,
    widgetLogo: images.widgetLogo.poshmark,
  },
  {
    id: '',
    img: images.socials.appStore,
    title: 'App Store',
    subTitle: 'App Store Tagg',
    link_type: ApplicationLinkWidgetLinkTypes.APP_STORE,
    type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
    locked: false,
    item_color_start: TaggShopGradientBg.AppStore.start,
    item_color_end: TaggShopGradientBg.AppStore.end,
    widgetLogo: images.widgetLogo.appStore,
  },
  // {
  //   id: '',
  //   img: images.widgets.shopify,
  //   title: 'Shopify',
  //   subTitle: 'Shopify TAGG',
  //   link_type: ApplicationLinkWidgetLinkTypes.SHOPIFY,
  //   type: ApplicationLinkWidgetTypes.APPLICATION_LINK,
  //   locked: false,
  // },
];

export const WidgetsURLConstructor = {
  [VideoLinkWidgetLinkTypes.PINTEREST]: {
    validator: (value: string): boolean => !!value.trim().match(PINTEREST),
    urlPlaceholder: 'https://www.pinterest.com',
    logoSmall: images.socials.Pinterest,
    title: 'Pinterest',
  },
  [ApplicationLinkWidgetLinkTypes.YOUTUBE_MUSIC]: {
    validator: (value: string): boolean => !!value.trim().match(YOUTUBEMUSIC),
    urlPlaceholder: 'https://www.youtubemusic.com',
    logoSmall: images.socials.Youtubemusic,
    title: 'Youtube Music',
  },
  [ApplicationLinkWidgetLinkTypes.TIDAL]: {
    validator: (value: string): boolean => !!value.trim().match(TIDAL),
    urlPlaceholder: 'https://www.tidal.com',
    logoSmall: images.socials.Tidal,
    title: 'Tidal',
  },
  [VideoLinkWidgetLinkTypes.VSCO]: {
    validator: (value: string): boolean => !!value.trim().match(VSCO),
    urlPlaceholder: 'https://www.vsco.com',
    logoSmall: images.socials.vsco,
    title: 'VSCO',
  },
  [VideoLinkWidgetLinkTypes.ONLYFANS]: {
    validator: (value: string): boolean => !!value.trim().match(ONLYFANS),
    urlPlaceholder: 'https://www.onlyfans.com',
    logoSmall: images.socials.OnlyFans,
    title: 'OnlyFans',
  },
  [ApplicationLinkWidgetLinkTypes.APPLE_MUSIC]: {
    validator: (value: string): boolean => !!value.trim().match(APPLE_MUSIC),
    urlPlaceholder: 'https://music.apple.com',
    logoSmall: images.socials.appleMusicBoxSmall,
    title: 'Apple Music',
  },
  [VideoLinkWidgetLinkTypes.YOUTUBE]: {
    validator: (value: string): boolean => !!value.trim().match(YOUTUBE),
    urlPlaceholder: 'https://youtube.com',
    logoSmall: images.socials.youtubeSmall,
    title: 'Youtube',
  },
  [SocialMediaTypes.FACEBOOK]: {
    validator: (value: string): boolean => !!value.trim().match(FACEBOOK),
    urlPlaceholder: 'Enter username',
    logoSmall: images.socials.facebookIconSmall,
    title: 'Facebook',
  },
  [SocialMediaTypes.INSTAGRAM]: {
    validator: (value: string): boolean => !!value.trim().match(INSTA_GRAM),
    urlPlaceholder: '@instagram',
    logoSmall: images.socials.instagramSmall,
    title: 'Instagram',
  },
  [SocialMediaTypes.SNAPCHAT]: {
    validator: (value: string): boolean => !!value.trim().match(SNAPCHAT),
    urlPlaceholder: '@snapchat',
    logoSmall: images.socials.snapchatSmall,
    title: 'Snapchat',
  },
  [SocialMediaTypes.TWITTER]: {
    validator: (value: string): boolean => !!value.trim().match(TWITTER),
    urlPlaceholder: '@twitter',
    logoSmall: images.socials.twitterSmall,
    title: 'Snapchat',
  },
  // [VideoLinkWidgetLinkTypes.YOUTUBE]: {
  //   validator: (value: string): boolean => !!value.trim().match(INSTAGRAM),
  //   urlPlaceholder: 'https://youtube.com',
  //   logoSmall: images.socials.youtubeSmall,
  //   title: 'Youtube',
  // },
  // pinterest: {
  //   validator: (value: string): boolean =>
  //     !!value.trim().match(/^(http|https)?:\/\/(?:www\.)?pinterest\.com\/.*(?=((\w|-)))/i),
  //   urlPlaceholder: 'https://pinterest.com',
  //   logoSmall: images.socials.pinterest,
  // },
  // snapchat: {
  //   validator: (value: string): boolean =>
  //     !!value.trim().match(/^(http|https)?:\/\/(?:www\.)?snapchat\.com\/.*(?=((\w|-)))/i),
  //   urlPlaceholder: 'https://snapchat.com',
  //   logoSmall: images.socials.snapchat,
  // },
  [ApplicationLinkWidgetLinkTypes.SOUNDCLOUD]: {
    validator: (value: string): boolean => !!value.trim().match(SOUNDCLOUD),
    urlPlaceholder: 'https://soundcloud.com',
    logoSmall: images.socials.soundcloud,
    title: 'Soundcloud',
  },
  [ApplicationLinkWidgetLinkTypes.DEEZER]: {
    validator: (value: string): boolean => !!value.trim().match(DEEZER),
    urlPlaceholder: 'https://www.deezer.com',
    logoSmall: images.socials.deezerSmall,
    title: 'Deezer',
  },
  [ApplicationLinkWidgetLinkTypes.SPOTIFY]: {
    validator: (value: string): boolean => !!value.trim().match(SPOTIFY),
    urlPlaceholder: 'https://open.spotify.com',
    logoSmall: images.socials.spotify,
    title: 'Spotify',
  },
  [VideoLinkWidgetLinkTypes.TIKTOK]: {
    validator: (value: string): boolean => !!value.trim().match(TIK_TOK),
    urlPlaceholder: 'https://tiktok.com',
    logoSmall: images.socials.tiktok,
    title: 'TikTok',
  },
  [VideoLinkWidgetLinkTypes.TWITCH]: {
    validator: (value: string): boolean => !!value.trim().match(TWITCH),
    urlPlaceholder: 'https://twitch.tv',
    logoSmall: images.socials.twitch,
    title: 'Twitch',
  },
  [ApplicationLinkWidgetLinkTypes.APP_STORE]: {
    validator: (value: string): boolean => !!value.trim().match(APP_STORE),
    urlPlaceholder: 'https://apps.apple.com',
    logoSmall: images.widgetLogo.appStoreLogo,
    title: 'App store',
  },
  [ApplicationLinkWidgetLinkTypes.APPLE_PODCAST]: {
    validator: (value: string): boolean => !!value.trim().match(APPLE_PODCAST),
    urlPlaceholder: 'https://podcasts.apple.com',
    logoSmall: images.widgetLogo.podcastLogo,
    title: 'Apple Podcast',
  },
  [ApplicationLinkWidgetLinkTypes.DEPOP]: {
    validator: (value: string): boolean => !!value.trim().match(DEPOP),
    urlPlaceholder: 'https://depop.com',
    logoSmall: images.widgetLogo.depopLogo,
    title: 'Depop',
  },
  [ApplicationLinkWidgetLinkTypes.ETSY]: {
    validator: (value: string): boolean => !!value.trim().match(ETSY),
    urlPlaceholder: 'https://www.etsy.com',
    logoSmall: images.widgetLogo.etsyLogo,
    title: 'Etsy',
  },
  [ApplicationLinkWidgetLinkTypes.AMAZON]: {
    validator: (value: string): boolean => {
      let split_value = value.split(' ');
      return !!split_value[split_value.length - 1].trim().match(AMAZON);
    },
    urlPlaceholder: 'https://www.amazon.com',
    logoSmall: images.widgetLogo.amazonLogo,
    title: 'Amazon',
  },
  [ApplicationLinkWidgetLinkTypes.SHOPIFY]: {
    validator: (value: string): boolean => !!value.trim().match(SHOPIFY),
    urlPlaceholder: 'https://www.shopify.com',
    logoSmall: images.widgets.shopify,
    title: 'Shopify',
  },
  [ApplicationLinkWidgetLinkTypes.POSHMARK]: {
    validator: (value: string): boolean => !!value.trim().match(POSHMARK),
    urlPlaceholder: 'https://www.poshmark.com',
    logoSmall: images.widgets.poshmark,
    title: 'Poshmark',
  },
  [GenericLinkWidgetTypes.ARTICLE]: {
    validator: (value: string): boolean => !!value.trim().match(WEBSITE),
    urlPlaceholder: 'https://www.portfolio.com',
    logoSmall: images.widgets.article,
    title: 'Article',
  },
  [GenericLinkWidgetTypes.WEBSITE]: {
    validator: (value: string): boolean => !!value.trim().match(WEBSITE),
    urlPlaceholder: 'https://www.portfolio.com',
    logoSmall: images.widgets.website,
    title: 'Website',
  },
  [GenericLinkWidgetTypes.DISCORD]: {
    validator: (value: string): boolean => !!value.trim().match(DISCORD),
    urlPlaceholder: 'https://www.discord.com',
    logoSmall: images.socials.discordSmall,
    title: 'Discord',
  },
  [GenericLinkWidgetTypes.EMAIL]: {
    validator: (value: string): boolean => !!value.trim().match(EMAIL),
    urlPlaceholder: 'Add a Email',
    logoSmall: images.widgets.email,
    title: 'Email',
  },
  [ApplicationLinkWidgetLinkTypes.AMAZON_AFFILIATE]: {
    validator: (value: string): boolean => !!value.trim().match(AMAZON),
    logoSmall: images.widgetLogo.amazonLogo,
    urlPlaceholder: 'https://www.amazon.com',
    title: 'Amazon Affiliate',
  },
  [GenericLinkWidgetTypes.LIKETOKNOWIT]: {
    validator: (value: string): boolean => !!value.trim().match(LIKETOKNOWIT),
    urlPlaceholder: 'https://www.liketoknowit.com',
    logoSmall: images.widgets.liketoknowit,
    title: 'LikeToKnowIt',
  },
};
