export const navigation = {
  chat: require('./chat.png'),
  chatClicked: require('./chat-clicked.png'),
  chatNotification: require('./chat-notifications.png'),
  home: require('./home.png'),
  homeClicked: require('./home-clicked.png'),
  newNotifications: require('./new-notifications.png'),
  newUpload: require('./new-upload.png'),
  notifications: require('./notifications.png'),
  notificationsClicked: require('./notifications-clicked.png'),
  profile: require('./profile.png'),
  profileClicked: require('./profile-clicked.png'),
  search: require('./search.png'),
  searchClicked: require('./search-clicked.png'),
  taggCircular: require('./tagg-circular.png'),
  taggCircularClicked: require('./tagg-circular-clicked.png'),
  upload: require('./upload.png'),
  uploadClicked: require('./upload-clicked.png'),
  momentClicked: require('./moment_focused.png'),
  moment: require('./moment_unfocused.png'),
  momentNotification: require('./moment_notify.png'),
  whats_new: require('./whats-new.png'),
};
