export enum AnalyticCategory {
  Moment = 'Moment',
  Notification = 'Notification',
  InviteFriends = 'InviteFriends',
  Camera = 'Camera',
  MomentUpload = 'MomentUpload',
  MomentEdit = 'MomentEdit',
  Profile = 'Profile',
  Settings = 'Settings',
  EditProfile = 'EditProfile',
  Login = 'Login',
  PasswordReset = 'PasswordReset',
  Onboarding = 'Onboarding',
  AddAPage = 'AddAPage',
  Taggs = 'Taggs',
  EditATagg = 'EditATagg',
  EditAPage = 'EditAPage',
  EditSkin = 'EditSkin',
  Insights = 'Insights',
  Leaderboard = 'Leaderboard',
}

export enum AnalyticVerb {
  Pressed = 'Pressed',
  Viewed = 'Viewed',
  Canceled = 'Canceled',
  Toggled = 'Toggled',
  Selected = 'Selected',
  Updated = 'Updated',
  Uploaded = 'Uploaded',
  Visited = 'Visited',
  Closed = 'Closed',
  Finished = 'Finished',
  Failed = 'Failed',
}
