export const tutorialGIFs = {
  addTagg: require('./add_tagg.json'),
  editSkin: require('./edit_skin.json'),
  editTagg: require('./edit_tagg.json'),
  moments: require('./moments.json'),
  pages: require('./pages_new.json'),
  kid: require('./kid.json'),
  shareProfile: require('./share_profile.json'),
  pulsating: require('./circle.json'),
  pulsatingLong: require('./circle_long.json'),
  coin: require('./coin.json'),
  animated_mysterybox: require('./button_animation.json'),
  rewardcoin_ten: require('./coin_ten.json'),
  rewardcoin_hundrade: require('./coin_hundrade.json'),
  rewardcoin_thousand: require('./coin_thousabd.json'),
  rewardcoin_fivehundrad: require('./coin_fivehundrade.json'),
  rewardcoin_fivethousand: require('./coin_fivethousand.json'),
  reward_insight: require('./insights.json'),
  reward_tools: require('./creator_tools.json'),
  reward_experience: require('./content_experience.json'),
};
