export const Images = {
  LandingPageBg: {
    Background_Image: require('./landingPage/landingPageBg.png'),
    Logo: require('./images/main/logo.png'),
    Fb_Icon: require('./socials/facebook-icon.png'),
    Google_Icon: require('./socials/google-icon.png'),
  },
  SignUp: {
    RedCross: require('./images/red-cross.png'),
    GreenCheck: require('./images/main/green-check.png'),
    InstagramIcon: require('./icons/Instagram.png'),
    TiktokIcon: require('./icons/Tiktok.png'),
  },
  WaitingList: {
    Background_Imag: require('./images/bg-image-insta.png'),
  },
  Onboarding: {
    BuildProfileIllustration: require('./images/BuildProfileIllustration.png'),
    ConfettiBackground: require('./images/ConfettiBackground.png'),
  },
  Skins: {
    One: require('./skins/Template1.png'),
    Two: require('./skins/Template2.png'),
    Three: require('./skins/Template3.png'),
    Four: require('./skins/Template4.png'),
    Five: require('./skins/Template5.png'),
  },
  Interest: [
    require('./images/Art.png'),
    require('./images/College.png'),
    require('./images/Sport.png'),
    require('./images/Fitness.png'),
    require('./images/Outdoor.png'),
    require('./images/Nature.png'),
    require('./images/Travel.png'),
    require('./images/Blogger.png'),
    require('./images/Gaming.png'),
    require('./images/Engineering.png'),
    require('./images/Food.png'),
    require('./images/Finance.png'),
    require('./images/Design.png'),
    require('./images/Health.png'),
    require('./images/Journalism.png'),
    require('./images/Legal.png'),
    require('./images/Film.png'),
    require('./images/Photography.png'),
    require('./images/Reading.png'),
    require('./images/Music.png'),
    require('./images/Cooking.png'),
    require('./images/Dance.png'),
    require('./images/Writting.png'),
    require('./images/Yoga.png'),
    require('./images/Astronomy.png'),
    require('./images/Fishing.png'),
    require('./images/Politics.png'),
    require('./images/Tech.png'),
    require('./images/Podcast.png'),
    require('./images/Marketing.png'),
    require('./images/Fashion.png'),
    require('./images/Beauty.png'),
    require('./images/Entrepreneur.png'),
    require('./images/DIY.png'),
    require('./images/Jewlery.png'),
  ],
};

export const Videos = {
  tagg_intro_video: require('./videos/tagg_intro_video.mp4'),
  tagg_load_screen: require('./videos/tagg_load_screen.mp4'),
  moments_login_video: require('./videos/moments_login_video.mp4'),
  analytics_intro_video: require('./videos/analytics_intro_video.mp4'),
  onboarding_video: require('./videos/onBoardingVideo.mp4'),
  coin_introduction_video: require('./videos/coin_introduction_video.mp4'),
};
