export const settings = {
  discord: require('./discord.png'),
  community: require('./communitysetting.png'),
  communitysetting: require('./community.png'),
  blockedWhite: require('./blocked-white.png'),
  editProfile: require('./edit-profile.png'),
  lockWhite: require('./lock-white.png'),
  privacyPolicy: require('./privacypolicy.png'),
  settings: require('./settings.png'),
  settingsWhite: require('./settings-white.png'),
  termsOfUse: require('./termsofuse.png'),
  whiteArrow: require('./white-arrow.png'),
  insights: require('./Insights.png'),
  lock: require('./Lock.png'),
  insight_graph: require('./insight_graph.png'),
  //blockedProfile: require('./blocked_profile.png'),
  blockedProfile: require('./blocked_profile_high_reso.png'),
  Delete: require('./Trash.png'),
};
